#!/bin/bash
ACTION=${1}

function create_file() {
touch "${1}-12345"
}

function display_help() {
cat << EOF
Usage: ${0} {-c|--create|-h|--help}
OPTIONS:
	-h | --help	Display the command help
	-c | --create	Creat a new file
Examples:
	Display help:
		$ ${0} -h
	Create file:
		$ ${0} -c	<filename>
EOF
}

case "$ACTION" in
	-h|--help)
		display_help
		;;
	-c|--create)
		create_file "${2:-server}"
		;;
	*)
	echo "Usage ${0} {-c|-h}"
	exit 1
esac

