#!/bin/bash
ACTION=${1}
version="1.0.1"

function delete_file() {
rm "${1}-12345"
}

function create_file() {
touch "${1}-12345"
}

function show_version() {
echo $version
}

function display_help() {
cat << EOF
Usage: ${0} {-d|--delete|-c|--create|-h|--help}
OPTIONS:
	-h | --help	Display the command help
	-c | --create	Creat a new file
	-d | --delete	Delete file
	-v | --version	Show version
Examples:
	Display help:
		$ ${0} -h
	Create file:
		$ ${0} -c	<filename>
	Delete file:
		$ ${0} -d	<filename>
	Show version
		$ ${0} -v
EOF
}

case "$ACTION" in
	-h|--help)
		display_help
		;;
	-c|--create)
		create_file "${2:-server}"
		;;
	-d|--delete)
		delete_file "${2:-server}"
		;;
	-v|--version)
		show_version
		;;
	*)
	echo "Usage ${0} {-v|-d|-c|-h}"
	exit 1
esac

